### ISSUE TITLE
To drop SimChannels need to modify TruthMatching Utilities 

### ISSUE THREAD

**Issue by jzennamo** [SBNSoftware/sbndcode#103]
We have added an association between hits, MCParticles, and their IDEs. This is all the information needed for truth matching and much lighter than SimChannels. There are truth matching utilities that need to be modified to accommodate this new association

**Comment by jzennamo** [comment]
Could you point to the functions that need to be modified?

**Comment by absolution1** [comment]
Hi @jzennamo 
Slightly crossed wires: I'm thinking that we should change the underlying implementation in the backtracker so that we don't have to change any of the user-facing truth matching interfaces. 
The rough idea would be that the backtracker would figure out, under the hood, whether it needs to use the sim channels or the underlying association data product you mentioned above.
For reference, the truth matching utilities are here: https://github.com/LArSoft/larsim/blob/develop/larsim/Utils/TruthMatchUtils.h

**Comment by cjbackhouse** [comment]
Is there a need to dynamically support both? I'm sure it would be simpler code-wise to just have a clean break. But maybe since it takes time to produce new files we will have to support old and new for a little while?

**Comment by bear-is-asleep** [comment]
I'm assuming this was completed given simchannel is able to be dropped now.
