### ISSUE TITLE
OpT0Finder Is SegFaulting in v09_28_01

### ISSUE THREAD

**Issue by jzennamo** [SBNSoftware/sbndcode#163]
in SBNDCode v09_28_01 it looks like OpT0Finder has a few issues which it either seg faults or gives the following error:
`Error: Invalid optical detector type. 0 = rectangular, 1 = dome, 2 = disk. Or corrections for chosen optical detector type missing.` before crashing

**Comment by jzennamo** [comment]
I removed it from the reco2 fcl files in this PR: https://github.com/SBNSoftware/sbndcode/pull/162

**Comment by marcodeltutto** [comment]
This problem is related to the fact that the SBND OpT0Finder currently uses the semi-analytical method located in the LegacyLArG4 directory (for ex, see [this include](https://github.com/SBNSoftware/sbncode/blob/develop/sbncode/OpT0Finder/flashmatch/Algorithms/PhotonLibHypothesis.h#L32)). This is needed to construct a flash hypothesis that is then matched to the reconstructed flashes.

This needs to be changed in the OpT0Finder to use the one in larsim instead of LegacyLArG4. In particular, the OpT0Finder needs to call the `detectedDirectHits` and `detectedReflectedHits` functions: 

https://github.com/SBNSoftware/sbncode/blob/05daec7ee8096d16886c0283d6f1af6454ff133d/sbncode/OpT0Finder/flashmatch/Algorithms/PhotonLibHypothesis.cxx#L84-L88

These functions in the new larg4 are located in `larsim/PDFastSimPAR_module.cc`:

https://github.com/LArSoft/larsim/blob/2d0a234522bae86187a8349ba072504deada06ec/larsim/PhotonPropagation/PDFastSimPAR_module.cc#L311-L320

But cannot be called from the OpT0Finder code because are private methods of the `PDFastSimPAR EDProducer`.

To fix this issue we would need to change `larsim/PDFastSimPAR_module.cc`, possibly factorizing the `detectedDirectHits` and `detectedReflectedHits` functions in a separate class that can be called also by the OpT0Finder code.

**Comment by pgreen135** [comment]
I think factorising these functions into a separate class would be useful/cleaner in general, and it has been my intention to do that for a while now. Though I likely won't have time to do this in the very near future - if this is wanted immediately, could the same 
approach as taken in the legacy code be used?

**Comment by marcodeltutto** [comment]
Yes, I think using the same approach as in the legacy code will be fine (having these functions in a separate "OpFastScintillation" class which is then called by both the PDFastSimPAR and OpT0Finder codes)

**Comment by pgreen135** [comment]
okay, I'll try work on this

**Comment by wesketchum** [comment]
@pgreen135 any update on this?

**Comment by pgreen135** [comment]
@wesketchum this is top of my list to do now, and I will hopefully have the changes needed in place by mid next week. This requires some restructuring in larsim though (moving these functions into their own classes), so will need approval from the larsoft team

**Comment by marcodeltutto** [comment]
Thanks @pgreen135! I'll work on it in the next days

**Comment by pgreen135** [comment]
@marcodeltutto the branch has now been tested and appears to be working as expected so I am planning to open a larsoft PR today for this to start that process, unless there are any issues / requests from your side beforehand for the opt0finder?

**Comment by marcodeltutto** [comment]
Sounds good @pgreen135, I haven't had the time to look over it but please open the PR

**Comment by pgreen135** [comment]
Re-opening as I hadn't meant this to be closed. @marcodeltutto https://github.com/LArSoft/larsim/pull/84 has now been included in v09_40_00, so the OpT0Finder can be re-activated once fixed. When you do get a chance to look at this, can you make these changes on a branch compatible with the SBN2021C releases --- it would be good to get this included in the 2022A release
