### ISSUE TITLE
Conflicting Treatment of TrackIDs

### ISSUE THREAD

**Issue by bear-is-asleep** [SBNSoftware/sbndcode#401]
I’ve been looking into the track IDs for the rockbox + cosmics sample [here](https://github.com/SBNSoftware/sbndcode/blob/7a983cc25387ca28f45f49fe70a40e666bac12cc/sbndcode/JobConfigurations/standard/gen/overlay/prodoverlay_corsika_cosmics_proton_genie_rockbox_sce.fcl) and noticed they had different ancestory trackIDs than the tpc + cosmics sample [here](https://github.com/SBNSoftware/sbndcode/blob/7a983cc25387ca28f45f49fe70a40e666bac12cc/sbndcode/JobConfigurations/standard/gen/overlay/prodoverlay_corsika_cosmics_proton_genie_nu_spill_tpc_sbnd.fcl). The rockbox sample uses trackID offsets to merge the two samples, but the tpc sample does not. This leads to a different structure in how the parent trackIDs are set. In the rockbox sample the parent IDs are set equal to the offset value for primaries, whereas the tpc sample sets it equal to the offset for primaries (attached example images). Is there a reason the two generators merge the neutrino and cosmic samples together differently? I would think we’d want to treat the trackIDs in the rockbox sample the same way we treat them in the tpc sample. 

![image](https://github.com/SBNSoftware/sbndcode/assets/67704640/8480b2bb-963c-4afc-907e-a95a8c9c7ead)
![image](https://github.com/SBNSoftware/sbndcode/assets/67704640/b7ab75b0-fa11-43e3-a4d6-3c638b136c7d)

**Comment by marcodeltutto** [comment]
Thanks for spotting this, @bear-is-asleep. From a quick look, I think the issue is that MergeSimSources doesn't update the track ID for the mother MCParticle. For the rockbox + cosmic dirt sample we simulate neutrino and cosmic interaction separately with Geant4, and we then merge them with MergeSimSources. When MCParticles from two collections are merged, an offset is added to both track IDs (in this case 10000000 and 20000000) to keep uniqueness. This offset is added to the MCParticle and all the daughters, but the mother is not updated. 

The merging happens basically with this line: https://github.com/LArSoft/larsim/blob/26da305b04445bc148f5e2600bb9cb3756d887ab/larsim/MergeSimSources/MergeSimSources.cxx#L50

The addition of the offset is done with this constructor:
https://github.com/NuSoftHEP/nusimdata/blob/aa41b26abba6e2b89d08ac2b77045929afdafe67/nusimdata/SimulationBase/MCParticle.cxx#L86-L107

which doesn't update `fmother`.
I don't see a particular reason why `fmother` shouldn't be updated, I belived this was just missed. This should be fixed in the MCParticle class.

**Comment by bear-is-asleep** [comment]
Hi @marcodeltutto thanks for the comment! It does look like constructor updates `fmother` in this line - https://github.com/NuSoftHEP/nusimdata/blob/aa41b26abba6e2b89d08ac2b77045929afdafe67/nusimdata/SimulationBase/MCParticle.cxx#L99

**Comment by marcodeltutto** [comment]
Ah good point! Somehow I completely missed that line :sweat_smile:
Ok then I don't see an obvious issue, need to do some further digging!

**Comment by bear-is-asleep** [comment]
Ah okay I can dig a bit more. Just making sure there wasn't a good reason for doing things this way, I'll keep searching. Thanks!

**Comment by bear-is-asleep** [comment]
@marcodeltutto I also saw in [nusim](https://github.com/NuSoftHEP/nusimdata/issues/3) there was an issue with how the constructor modifies the mother ID. One solution is to not modify the mother ID when offsetting the track IDs, though this may be an issue with particles with genuine mothers. We could modify it if and only if the mother ID is not 0. Alternatively we can just add a set function to the class so one could just set the mother id a priori if they wish [here](https://github.com/NuSoftHEP/nusimdata/pull/5). Do you have any insight on how to handle this?

**Comment by marcodeltutto** [comment]
Hi @bear-is-asleep, right, not modifying the mother's ID is not ideal as we lose the way to go back to the parent, but doing it only if the mother is not 0 sounds like a possible solution to me. In the end, the ID of 0 doesn't really point to a particle but only tells us that that particle is a primary, so we shouldn't add offsets there.

**Comment by bear-is-asleep** [comment]
For now the solution is [here](https://github.com/LArSoft/larsim/pull/131) for MCTracks. But I can ask more about this in the issue mentioned above to see if there's interest in updating the constructor.

**Comment by marcodeltutto** [comment]
Yes, sounds good, thanks @bear-is-asleep!

**Comment by bear-is-asleep** [comment]
This [PR](https://github.com/LArSoft/larsim/pull/131) is able to handle track ID offsets in MCReco using a fcl parameter.
