### ISSUE TITLE
TPC boundary is wrong

### ISSUE THREAD

**Issue by ikatza** [SBNSoftware/sbndcode#75]
I observed this issue a while back, when working on the light simulation. Actually I opened an issue in LArSoft redmine: https://cdcvs.fnal.gov/redmine/issues/24430

The X position of the cathode is wrong. It reports to be at +- 2.6 cm. It should be something closer to 0 cm.

```
TPC: 0
MinX():    -200
MaxX():    -2.6

TPC: 1
MinX():    2.6
MaxX():    200
```

I don't know if this is an issue with the geometry functions upstream, the way the SBND geometry is parsed or the actual geometry file.

**Comment by wesketchum** [comment]
@ikatza is this still an outstanding issue? If so, we should get someone on it...

**Comment by ikatza** [comment]
@mrguzzo or @gustavogx, should comment. But I believe the new geometry update solves this, would need to check when it gets merged.

**Comment by gustavogx** [comment]
Yes, it should be zero now. I moved half of the cathode inside the TPC so its logical volume can start at the right position.
Could someone please check again with the latest version, before merging? 

feature/NewGeometry_v2

**Comment by pgreen135** [comment]
@gustavogx if this is ready to be merged, please submit a pull request and I will include it in the next release

**Comment by gustavogx** [comment]
Not, it is not. We are still make some adjustments. As soon as it is, I'll make a pull request. Thanks!

**Comment by wesketchum** [comment]
(assigning gustavo, just for bookkeeping)

**Comment by ikatza** [comment]
In my opinion PR don't necessarily are _finished features_. I think it's ok to open them to get the review going and so that people who are interested can take a look or at least are aware what's coming. That's certainly the approach I take. Github is smart enough to add on new commits to the PR and update the revisions as they change.

**Comment by marcodeltutto** [comment]
Hi! I would suggest to open a PR in a draft stage if it is not ready to be merged yet, so there is no risk that it gets merged accidentally.

Regarding the minX, maxX, this is what I get with the geometry in `feature/NewGeometry_v2`:
```
>>> import SBNDservices as services
>>> geo_service = services.ServiceManager('Geometry')
>>> geo_service.TPC(0, 0).MinX()
-202.20000000000002
>>> geo_service.TPC(0, 0).MaxX()
0.0
>>>
>>> geo_service.TPC(0, 0).ActiveWidth()
201.3
>>> geo_service.TPC(1, 0).MinX()
0.0
>>> geo_service.TPC(1, 0).MaxX()
202.20000000000002
```

Do we really want `MinX()` to be exactly zero? I think this means that in LArSoft the position of the foils on the cathode is interpreted to be at (for TPC 1) `MinX() = 0`. I don’t know what the cathode thickness is, but I assume it is a few millimeters? So `MinX()` should return something like `cathode_thickness/2`.

Also, I think even if `TPC::MinX()` returns 0, that does not mean that we get ionization signals at x=0, because the first millimeters are occupied by the cathode, which is not made of LAr. But then if we ask for the `TPC::ActiveWidth()`, this returns the width of the `volTPCActive` volume, which includes the cathode too.

**Comment by ikatza** [comment]
Hi Marco,

Can you please check what do you get from
```
geom.TPC(0, 0).GetCathodeCenter().X()
```
that's what is being called in the light simulation.

It certainly would be better if it returned the actual few mm value. But don't think it has a large significance, if in deed no ionisation is produced at x=0 then no light is produced either. As such the bias is restricted to the distance that light travels from the ionisation, to the foils and back to the detectors. If the foils are 4 mm in thickness, that's 0.2 cm over at least 200 cm. So at most 0.1% bias.

**Comment by marcodeltutto** [comment]
Hi Iker! I get 0 also for the cathode center X:

```
>>> geo_service.TPC(0, 0).GetCathodeCenter().X()
0.0
```

I agree this is not significant for the amount of light and ionization produced. The reason I was raising this issue is because it was noticed during drift velocity studies. A few mm make a noticeable difference when you estimate the drift velocity from the time of the hits and the detector width. If it's too hard to change this is probably fine as far as we remember about it when we need an accurate value of the detector active width.
