### ISSUE TITLE
XARAPUCA digitiser clock not set correctly

### ISSUE THREAD

**Issue by ikatza** [SBNSoftware/sbndcode#78]
Currently the digitiser clock of PMTs and (X)ARAPUCAS is set to 500 MHz. That's the clock of the CAEN v1730. However the DAPHNE electronics works at 80MHz. 

There's a set of XARAPUCAS on the middle of the detector that are connected to APSAIA electronics; preamplifiers and power supplies served by a microcontroller, these are also digitised by the CAEN v1730 boards an so have the same clock as PMTs at 500 MHz. 

This is set in this fcl file: https://github.com/SBNSoftware/sbndcode/blob/b923d663f48c19de2cb465cbc1ec6243dbbbccdc/sbndcode/Utilities/detectorclocks_sbnd.fcl#L13

We access and use this value with an incantation that looks like this:
```
auto const clockData = art::ServiceHandle<detinfo::DetectorClocksService const>()->DataForJob();
double fSampling = clockData.OpticalClock().Frequency(); // MHz
```

It comes from: https://github.com/LArSoft/lardataalg/blob/10b7a5bba3e236475f5eff83097f25686be24564/lardataalg/DetectorInfo/DetectorClocksData.h#L403

This clock is necessary to simulate the digitised waveforms:
https://github.com/SBNSoftware/sbndcode/blob/b923d663f48c19de2cb465cbc1ec6243dbbbccdc/sbndcode/OpDetSim/DigiArapucaSBNDAlg.cc#L395
a quick hack is to simply replace that line with:
```
params.frequency = 0.16 * clockData.OpticalClock().Frequency();
```

Another instance where is relevant is: 
https://github.com/SBNSoftware/sbndcode/blob/develop/sbndcode/OpDetSim/opDetSBNDTriggerAlg.cc
Where similar hacks could be made.

The other place where the clock is relevant is for OpHitFinding:
https://github.com/SBNSoftware/sbndcode/blob/develop/sbndcode/OpDetReco/OpHit/SBNDOpHitFinder_module.cc
There's no easy workaround or hack that I can think of to sort that.

I'm not advocating for hacks or quick work arounds, rather I'm highlighting the complexity of solving this issue. 

I don't have time myself to fix this, hopefully someone will find time to tackle this one.

**Comment by rodralva** [comment]
Hi Iker, @ggamezdiego,

I've been looking into the files where the OpticalClock appears. As Iker commented, there's no easy workoaround to fix it. The frequency is defined to be the same for all the event/events, so we'll need to add some lines that distingish between different readout channels (for all the files).

For the frequency value itself, we could set it from some fhicl file e.g. : 
https://github.com/SBNSoftware/sbndcode/blob/b923d663f48c19de2cb465cbc1ec6243dbbbccdc/sbndcode/OpDetSim/digi_arapuca_sbnd.fcl

Or we could change the MapAlg new field to contain numbers:
samplig: 500/80
instead of the daphne/apsaia types.
